#!/usr/bin/env python3
"""Generate docs/cli-reference.md from the live click command tree.

The reference cannot drift from the code: a pre-commit hook runs
`gen_cli_docs.py --check`, which fails the commit whenever the committed
file differs from what the current command tree produces (PLAN.md §6).

Never hand-edit docs/cli-reference.md.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import click

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from vrcli import __version__  # noqa: E402
from vrcli.cli.main import cli  # noqa: E402

TERMINAL_WIDTH = 100  # fixed so output does not depend on the invoking terminal

HEADER = f"""\
# `vr` CLI reference

<!-- AUTO-GENERATED by scripts/gen_cli_docs.py — never hand-edit.
     Regenerate with: python3 scripts/gen_cli_docs.py -->

Generated from vrcli {__version__}.

"""


def walk(cmd: click.Command, info_name: str, parent: click.Context | None = None):
    ctx = click.Context(
        cmd, info_name=info_name, parent=parent, terminal_width=TERMINAL_WIDTH
    )
    yield ctx
    if isinstance(cmd, click.Group):
        for name in sorted(cmd.commands):
            yield from walk(cmd.commands[name], name, ctx)


def generate() -> str:
    sections = []
    for ctx in walk(cli, "vr"):
        depth = ctx.command_path.count(" ")
        heading = "#" * min(depth + 2, 5)
        sections.append(
            f"{heading} `{ctx.command_path}`\n\n```\n{ctx.get_help()}\n```\n"
        )
    return HEADER + "\n".join(sections)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if docs/cli-reference.md is stale instead of writing it.",
    )
    args = parser.parse_args()

    target = REPO_ROOT / "docs" / "cli-reference.md"
    fresh = generate()

    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != fresh:
            print(
                f"{target.relative_to(REPO_ROOT)} is stale. "
                f"Run: python3 scripts/gen_cli_docs.py",
                file=sys.stderr,
            )
            return 1
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(fresh, encoding="utf-8")
    print(f"wrote {target.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
